ALTER DATABASE BINSight SET RECOVERY SIMPLE
GO

ALTER DATABASE BINSight SET RECOVERY FULL
GO

USE BINSight
GO
DBCC SHRINKFILE (N'BINSight_log' , 0, TRUNCATEONLY)
GO
USE master
GO

BACKUP DATABASE BINSight TO DISK = 'BINSight_UBCAfterStage1.bak' WITH INIT, COMPRESSION
GO

ALTER DATABASE BINSightBoc SET RECOVERY SIMPLE
GO

ALTER DATABASE BINSightBoc SET RECOVERY FULL
GO

USE BINSightBoc
GO
DBCC SHRINKFILE (N'BINSightBoc_log' , 0, TRUNCATEONLY)
GO
USE master
GO

BACKUP DATABASE BINSightBoc TO DISK = 'BINSightBoc_UBCAfterStage1.bak' WITH INIT, COMPRESSION
GO